function networkInput = GetNetworkInput(velocity, ...
                                        slopeAngle, ...
                                        breakTemp, ...
                                        constants)
    networkInput = [(velocity/constants.maxVelocity), ...,
                    (slopeAngle/constants.maxAngle), ...
                    (breakTemp/constants.maxTemp)];
end