function population = InitializePopulation(populationSize, nNeurons, activations)
    population = cell(populationSize, 1);
    for i = 1:populationSize
        weights = {{sqrt(2/3) * (2*rand(3, nNeurons) - 1), ...
                    sqrt(2/nNeurons) * (2*rand(nNeurons, 2) - 1)}};
        biases = {{zeros(1, nNeurons), ...
                  zeros(1, 2)}};
        individual = struct('weights', weights, ...
                            'biases', biases, ...
                            'activations', {activations}, ...
                            'numberOfLayers', 2);
        population{i} = individual;
    end
end
