function UpdateDrivingPlot(handles, drivingData)
    set(handles.angleHandle, 'XData', drivingData.positions, ...
                             'YData', drivingData.angles);
    set(handles.markers.angle, 'XData', drivingData.positions(end), ...
                               'YData', drivingData.angles(end));
    set(handles.pressureHandle, 'XData', drivingData.positions, ...
                                'YData', drivingData.pressures);
    set(handles.markers.pressure, 'XData', drivingData.positions(end), ...
                                  'YData', drivingData.pressures(end));
    set(handles.gearHandle, 'XData', drivingData.positions, ...
                            'YData', drivingData.gears);
    set(handles.markers.gear, 'XData', drivingData.positions(end), ...
                              'YData', drivingData.gears(end));
    set(handles.velocityHandle, 'XData', drivingData.positions, ...
                                'YData', drivingData.velocities);
    set(handles.markers.velocity, 'XData', drivingData.positions(end), ...
                                  'YData', drivingData.velocities(end));
    set(handles.breakTempHandle, 'XData', drivingData.positions, ...
                                 'YData', drivingData.temperatures);
    set(handles.markers.temperature, 'XData', drivingData.positions(end), ...
                                     'YData', drivingData.temperatures(end));
    drawnow;
end